
--PHASE 3: STAR SCHEMA (DIM + FACT)


-- DIM PART
CREATE OR REPLACE TABLE ANALYTICS.DIM_PART (
    PART_SK NUMBER AUTOINCREMENT,
    P_PARTKEY NUMBER,
    P_NAME STRING,
    P_MFGR STRING,
    P_BRAND STRING,
    P_TYPE STRING,
    P_SIZE NUMBER,
    P_CONTAINER STRING,
    P_RETAILPRICE FLOAT
);

INSERT INTO ANALYTICS.DIM_PART
SELECT * FROM RAW.PART;

-- DIM SUPPLIER
CREATE OR REPLACE TABLE ANALYTICS.DIM_SUPPLIER (
    SUPPLIER_SK NUMBER AUTOINCREMENT,
    S_SUPPKEY NUMBER,
    S_NAME STRING,
    S_ADDRESS STRING,
    S_NATIONKEY NUMBER,
    S_PHONE STRING,
    S_ACCTBAL FLOAT
);

INSERT INTO ANALYTICS.DIM_SUPPLIER
SELECT * FROM RAW.SUPPLIER;

-- DIM DATE
CREATE OR REPLACE TABLE ANALYTICS.DIM_DATE AS
SELECT DISTINCT
    O_ORDERDATE AS DATE_KEY,
    YEAR(O_ORDERDATE) AS YEAR,
    MONTH(O_ORDERDATE) AS MONTH,
    DAY(O_ORDERDATE) AS DAY
FROM RAW.ORDERS;

-- DIM REGION
CREATE OR REPLACE TABLE ANALYTICS.DIM_REGION AS
SELECT R.R_REGIONKEY, R.R_NAME, N.N_NATIONKEY, N.N_NAME
FROM RAW.REGION R
JOIN RAW.NATION N
ON R.R_REGIONKEY = N.N_REGIONKEY;

-- FACT TABLE
CREATE OR REPLACE TABLE ANALYTICS.FACT_SALES (
    SALES_SK NUMBER AUTOINCREMENT,
    ORDER_KEY NUMBER,
    CUSTOMER_SK NUMBER,
    PART_SK NUMBER,
    SUPPLIER_SK NUMBER,
    DATE_KEY DATE,
    QUANTITY NUMBER,
    PRICE FLOAT,
    DISCOUNT FLOAT,
    REVENUE FLOAT
);

INSERT INTO ANALYTICS.FACT_SALES
SELECT 
    O.O_ORDERKEY,
    DC.CUSTOMER_SK,
    DP.PART_SK,
    DS.SUPPLIER_SK,
    O.O_ORDERDATE,
    L.L_QUANTITY,
    L.L_EXTENDEDPRICE,
    L.L_DISCOUNT,
    (L.L_EXTENDEDPRICE * (1 - L.L_DISCOUNT))
FROM RAW.ORDERS O
JOIN RAW.LINEITEM L ON O.O_ORDERKEY = L.L_ORDERKEY
JOIN ANALYTICS.DIM_CUSTOMER DC ON O.O_CUSTKEY = DC.C_CUSTKEY AND DC.IS_ACTIVE = TRUE
JOIN ANALYTICS.DIM_PART DP ON L.L_PARTKEY = DP.P_PARTKEY
JOIN ANALYTICS.DIM_SUPPLIER DS ON L.L_SUPPKEY = DS.S_SUPPKEY;