
-- PHASE 5: SECURITY + PERFORMANCE


//Row Level Security
CREATE OR REPLACE ROW ACCESS POLICY REGION_POLICY
AS (REGION STRING) 
RETURNS BOOLEAN ->
    CURRENT_ROLE() = 'ACCOUNTADMIN'
    OR REGION = 'ASIA';

ALTER TABLE ANALYTICS.SALES_SUMMARY
ADD ROW ACCESS POLICY REGION_POLICY ON (REGION);

-- Masking Policy
CREATE OR REPLACE MASKING POLICY PHONE_MASK
AS (VAL STRING) 
RETURNS STRING ->
    CASE 
        WHEN CURRENT_ROLE() = 'ACCOUNTADMIN' THEN VAL
        ELSE 'XXXX-XXXX'
    END;

ALTER TABLE ANALYTICS.DIM_CUSTOMER
MODIFY COLUMN C_PHONE SET MASKING POLICY PHONE_MASK;

CREATE OR REPLACE SHARE SALES_SHARE;

GRANT USAGE ON DATABASE SALES_DWH TO SHARE SALES_SHARE;
GRANT USAGE ON SCHEMA ANALYTICS TO SHARE SALES_SHARE;
GRANT SELECT ON TABLE ANALYTICS.FACT_SALES TO SHARE SALES_SHARE;

ALTER TABLE ANALYTICS.FACT_SALES
CLUSTER BY (DATE_KEY);