
--PHASE 2: PIPELINE + SCD2 + AUDIT


-- Cleanup (safe re-run)
DROP PROCEDURE IF EXISTS CORE.LOAD_CUSTOMER_PIPELINE();
DROP STREAM IF EXISTS RAW.CUSTOMER_STREAM;
DROP TABLE IF EXISTS STAGING.CUSTOMER_STG;
DROP TABLE IF EXISTS CORE.DIM_CUSTOMER;
DROP TABLE IF EXISTS CORE.AUDIT_LOG;



CREATE OR REPLACE TABLE STAGING.CUSTOMER_STG (
    C_CUSTKEY NUMBER,
    C_NAME STRING,
    C_ADDRESS STRING,
    C_NATIONKEY NUMBER,
    C_PHONE STRING,
    C_ACCTBAL FLOAT,
    C_MKTSEGMENT STRING,
    C_COMMENT STRING,
    LOAD_TS TIMESTAMP
);

-- Stream for CDC
CREATE OR REPLACE STREAM RAW.CUSTOMER_STREAM
ON TABLE RAW.CUSTOMER;

//SCD TYPE 2

CREATE OR REPLACE TABLE CORE.DIM_CUSTOMER (
    CUSTOMER_SK NUMBER AUTOINCREMENT,
    C_CUSTKEY NUMBER,
    C_NAME STRING,
    C_ADDRESS STRING,
    C_NATIONKEY NUMBER,
    C_PHONE STRING,
    C_ACCTBAL FLOAT,
    C_MKTSEGMENT STRING,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    IS_ACTIVE BOOLEAN
);

--Audit log
CREATE OR REPLACE TABLE CORE.AUDIT_LOG (
    JOB_NAME STRING,
    RUN_TIME TIMESTAMP,
    STATUS STRING,
    ROWS_PROCESSED NUMBER
);

--PIPELINE LOGIC

CREATE OR REPLACE PROCEDURE CORE.LOAD_CUSTOMER_PIPELINE()
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE ROW_COUNT NUMBER;

BEGIN

-- Clear staging
TRUNCATE TABLE STAGING.CUSTOMER_STG;

-- Load incremental data
INSERT INTO STAGING.CUSTOMER_STG
SELECT 
    C_CUSTKEY, C_NAME, C_ADDRESS, C_NATIONKEY,
    C_PHONE, C_ACCTBAL, C_MKTSEGMENT, C_COMMENT,
    CURRENT_TIMESTAMP()
FROM RAW.CUSTOMER_STREAM
WHERE METADATA$ACTION = 'INSERT';

-- Count processed rows
SELECT COUNT(*) INTO :ROW_COUNT FROM STAGING.CUSTOMER_STG;

-- Expire old records (SCD2)
UPDATE CORE.DIM_CUSTOMER T
SET END_DATE = CURRENT_TIMESTAMP(),
    IS_ACTIVE = FALSE
FROM STAGING.CUSTOMER_STG S
WHERE T.C_CUSTKEY = S.C_CUSTKEY
AND T.IS_ACTIVE = TRUE;

-- Insert new records
INSERT INTO CORE.DIM_CUSTOMER (
    C_CUSTKEY, C_NAME, C_ADDRESS, C_NATIONKEY,
    C_PHONE, C_ACCTBAL, C_MKTSEGMENT,
    START_DATE, END_DATE, IS_ACTIVE
)
SELECT 
    S.C_CUSTKEY, S.C_NAME, S.C_ADDRESS, S.C_NATIONKEY,
    S.C_PHONE, S.C_ACCTBAL, S.C_MKTSEGMENT,
    CURRENT_TIMESTAMP(), NULL, TRUE
FROM STAGING.CUSTOMER_STG S;

-- Audit log
INSERT INTO CORE.AUDIT_LOG
VALUES ('LOAD_CUSTOMER_PIPELINE', CURRENT_TIMESTAMP(), 'SUCCESS', :ROW_COUNT);

RETURN 'PIPELINE SUCCESS';

END;
$$;

-- Run pipeline
CALL CORE.LOAD_CUSTOMER_PIPELINE();