
-- PHASE 1: SETUP + DATA INGESTION



CREATE OR REPLACE DATABASE SALES_DWH;


USE DATABASE SALES_DWH;

--Create Schemas (Medallion Architecture)
CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA STAGING;
CREATE OR REPLACE SCHEMA CORE;
CREATE OR REPLACE SCHEMA ANALYTICS;


CREATE OR REPLACE WAREHOUSE COMPUTE_WH
WITH WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

USE WAREHOUSE COMPUTE_WH;

--TPCH DATA

CREATE OR REPLACE TABLE RAW.CUSTOMER AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;

CREATE OR REPLACE TABLE RAW.ORDERS AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS;

CREATE OR REPLACE TABLE RAW.LINEITEM AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM;

CREATE OR REPLACE TABLE RAW.PART AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART;

CREATE OR REPLACE TABLE RAW.SUPPLIER AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER;

CREATE OR REPLACE TABLE RAW.NATION AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION;

CREATE OR REPLACE TABLE RAW.REGION AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION;

--Internal stage

CREATE OR REPLACE STAGE RAW.INTERNAL_STAGE;


COPY INTO @RAW.INTERNAL_STAGE/customer_data.csv
FROM RAW.CUSTOMER
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"')
HEADER = TRUE
SINGLE = TRUE;


CREATE OR REPLACE TABLE RAW.CUSTOMER_RELOAD LIKE RAW.CUSTOMER;

COPY INTO RAW.CUSTOMER_RELOAD
FROM @RAW.INTERNAL_STAGE/customer_data.csv
FILE_FORMAT = (TYPE = CSV SKIP_HEADER=1)
ON_ERROR = 'CONTINUE';

-- Streams

CREATE OR REPLACE STREAM RAW.ORDERS_STREAM
ON TABLE RAW.ORDERS;


INSERT INTO RAW.ORDERS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS LIMIT 5;


CREATE OR REPLACE TASK LOAD_ORDERS_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
AS
INSERT INTO STAGING.ORDERS_STG
SELECT * FROM RAW.ORDERS_STREAM;

ALTER TASK LOAD_ORDERS_TASK RESUME;