
-- PHASE 4: DYNAMIC TABLES (REAL-TIME ANALYTICS)


DROP DYNAMIC TABLE IF EXISTS ANALYTICS.SALES_SUMMARY;
DROP DYNAMIC TABLE IF EXISTS ANALYTICS.SUPPLIER_PERFORMANCE;


CREATE OR REPLACE DYNAMIC TABLE ANALYTICS.SALES_SUMMARY
TARGET_LAG = '1 MINUTE'
WAREHOUSE = COMPUTE_WH
AS
SELECT 
    DR.R_NAME AS REGION,
    DD.YEAR,
    DD.MONTH,
    SUM(CAST(F.REVENUE AS NUMBER(18,2))) AS TOTAL_SALES,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY
FROM ANALYTICS.FACT_SALES F
JOIN ANALYTICS.DIM_DATE DD ON F.DATE_KEY = DD.DATE_KEY
JOIN ANALYTICS.DIM_CUSTOMER DC ON F.CUSTOMER_SK = DC.CUSTOMER_SK
JOIN ANALYTICS.DIM_REGION DR ON DC.C_NATIONKEY = DR.N_NATIONKEY
GROUP BY DR.R_NAME, DD.YEAR, DD.MONTH;

-- Supplier performance
CREATE OR REPLACE DYNAMIC TABLE ANALYTICS.SUPPLIER_PERFORMANCE
AS
SELECT 
    DS.S_NAME,
    SUM(CAST(F.REVENUE AS NUMBER(18,2))) AS TOTAL_REVENUE
FROM ANALYTICS.FACT_SALES F
JOIN ANALYTICS.DIM_SUPPLIER DS 
ON F.SUPPLIER_SK = DS.SUPPLIER_SK
GROUP BY DS.S_NAME;